### ISSUE TITLE
Go client fails to compile on FreeBSD 14: missing function getSendQueueLen

### ISSUE THREAD

**Issue by moonetic** [cadence-workflow/cadence-go-client#1394]
**Describe the bug**
When trying to compile on FreeBSD 14, the compile fails with following key message: missing function getSendQueueLen.
This isuue regards tchannel-go repository.
An issue has been opened there but it hangs for a while:
https://github.com/uber/tchannel-go/issues/914

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
Try to compile a project with dependency to current repository on FreeBSD 14, if fails because of https://github.com/uber/tchannel-go issue.

**Expected behavior**
Compilation is successfull

**Comment by moonetic** [comment]
@ibarrajo hey, I noticed that the PR on the issue just hangs there, how can we get a review on that?

**Comment by ibarrajo** [comment]
I pinged a maintainer at Uber to review your PR =]

**Comment by ibarrajo** [comment]
@moonetic it's been merged: https://github.com/uber/tchannel-go/pull/925
